Repository gamedig/node-gamedig, pull requests merged in 2023-09, with the labels that each got.

#348 Add Creativerse (2017) support.
  CHANGELOG.md
  GAMES_LIST.md
  games.txt
Labels: enhancement, protocol

#349 Replace compressjs by seek-bzip
  CHANGELOG.md
  package-lock.json
  package.json
  protocols/valve.js
Labels: bug, external

#353 Add `The Isle` support.
  CHANGELOG.md
  GAMES_LIST.md
  games.txt
Labels: enhancement

#363 Add `Eco` (2018) support.
  CHANGELOG.md
  GAMES_LIST.md
  games.txt
  protocols/eco.js
  protocols/index.js
Labels: enhancement, protocol

#360 Add Core Keeper support
  CHANGELOG.md
  GAMES_LIST.md
  games.txt
Labels: enhancement

#354 Update CS2D
  GAMES_LIST.md
  games.txt
  protocols/cs2d.js
Labels: protocol

#367 Add The Forest (2014) support.
  CHANGELOG.md
  GAMES_LIST.md
  games.txt
Labels: enhancement

#368 Add Operation: Harsh Doorstop support.
  CHANGELOG.md
  GAMES_LIST.md
  games.txt
Labels: enhancement

#369 Add Insurgency: Modern Infantry Combat support.
  CHANGELOG.md
  GAMES_LIST.md
  games.txt
Labels: enhancement
